services:
  rz263-bot:
    build: .
    container_name: rz263_schedule_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # Зберігаємо кеш розкладу та базу підписників на хості
      - ./data:/app/data
    environment:
      - TZ=Europe/Kyiv
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
